export const sorular =[
    {
        id:'1',
        soru:'html açılımı nedir',
        ans1:'Hayperx',
        ans2:'alic',
        ans3:'pls',
        ans4:'malloc',
        cevap:'Hayperx',
        verilencevap:'',
    },
    {
        id:'2',
        soru:'Aşşağıdakilerden Hangisi En Buyuk Başlıktır',
        ans1:'h3',
        ans2:'h6',
        ans3:'h1',
        ans4:'h2',
        cevap:'h1',
        verilencevap:'',
    },
    {
        id:'3',
        soru:'italik yazı hangi etiket sayesinde olur',
        ans1:'p',
        ans2:'h6',
        ans3:'b',
        ans4:'i',
        cevap:'i',
        verilencevap:'',
    },
    {
        id:'4',
        soru:'<style> tagı hangi tag içine yazılır',
        ans1:'<head>',
        ans2:'<body>',
        ans3:'<title>',
        ans4:'<script>',
        cevap:'<head>',
        verilencevap:'',
    },
    {
        id:'5',
        soru:'hangi tag bir alt satıra indirir',
        ans1:'<br>',
        ans2:'<body>',
        ans3:'<hr>',
        ans4:'<span>',
        cevap:'<br>',
        verilencevap:'',
    },
    {
        id:'6',
        soru:'<ul> nedir ?',
        ans1:'Sırasız liste başlatma damgasıdır',
        ans2:'Tanımlı liste başlatma damgasıdır',
        ans3:'Sıralı liste başlatma damgasıdır',
        ans4:'Hiçbiri',
        cevap:'Sırasız liste başlatma damgasıdır',
        verilencevap:'',
    },
    {
        id:'7',
        soru:'bir sayfanın başlığı hangi etiketler arasına yazılır',
        ans1:'<br>',
        ans2:'<body>',
        ans3:'<title>',
        ans4:'<form>',
        cevap:'<title>',
        verilencevap:'',
    },
    {
        id:'8',
        soru:'yazıyı kalın yapma etiketi hangisidir',
        ans1:'u',
        ans2:'i',
        ans3:'b',
        ans4:'p',
        cevap:'b',
        verilencevap:'',
    },
    {
        id:'9',
        soru:'html de linkin yeni sayfada açılmasını hangisi yapar',
        ans1:'target="_blank"',
        ans2:'target="_new"',
        ans3:'target="_self"',
        ans4:'target="_top"',
        cevap:'target="_blank"',
        verilencevap:'',
    },
    {
        id:'10',
        soru:'html de kayan yazı nasıl yapılır',
        ans1:'p',
        ans2:'marquee',
        ans3:'iframe',
        ans4:'input',
        cevap:'marquee',
        verilencevap:'',
    },
    {
        id:'11',
        soru:'Aşşağıdakilerden hangisi link oluşturur',
        ans1:'<br>',
        ans2:'<a>',
        ans3:'<link>',
        ans4:'<input>',
        cevap:'<a>',
        verilencevap:'',
    },
    {
        id:'12',
        soru:'Hangisi resim öğesi oluşturur',
        ans1:'<picture>',
        ans2:'<image>',
        ans3:'<img>',
        ans4:'<pic>',
        cevap:'<img>',
        verilencevap:'',
    },
    {
        id:'13',
        soru:'Hangisi hatalı bir etikettir',
        ans1:'<h5>',
        ans2:'<h7>',
        ans3:'<h6>',
        ans4:'<h4>',
        cevap:'<h7>',
        verilencevap:'',
    },
    {
        id:'14',
        soru:'<b> etiketi hangisi ile eşdeğerdir',
        ans1:'<u>',
        ans2:'<em>',
        ans3:'<strong>',
        ans4:'<ol>',
        cevap:'<strong>',
        verilencevap:'',
    },
    {
        id:'15',
        soru:'html dosya uzantısı nedir',
        ans1:'.css',
        ans2:'.htm',
        ans3:'.hltm',
        ans4:'.html',
        cevap:'.html',
        verilencevap:'',
    },
]